export default {
  availability: {
    ticket_type: [
      {
        price_band: [
          {
            absolute_saving: 0.0,
            allows_leaving_single_seats: 'always',
            discount_code: '',
            discount_desc: '',
            is_offer: false,
            non_offer_sale_combined: 35.0,
            non_offer_sale_seatprice: 31.0,
            non_offer_sale_surcharge: 4.0,
            number_available: 8,
            percentage_saving: 0,
            price_band_code: 'A/pool',
            price_band_desc: 'Band A',
            sale_combined: 35.0,
            sale_seatprice: 31.0,
            sale_surcharge: 4.0,
          },
          {
            absolute_saving: 0.0,
            allows_leaving_single_seats: 'always',
            discount_code: '',
            discount_desc: '',
            is_offer: false,
            non_offer_sale_combined: 29.0,
            non_offer_sale_seatprice: 26.0,
            non_offer_sale_surcharge: 3.0,
            number_available: 8,
            percentage_saving: 0,
            price_band_code: 'B/pool',
            price_band_desc: 'Band B',
            sale_combined: 29.0,
            sale_seatprice: 26.0,
            sale_surcharge: 3.0,
          },
          {
            absolute_saving: 0.0,
            allows_leaving_single_seats: 'always',
            discount_code: '',
            discount_desc: '',
            is_offer: false,
            non_offer_sale_combined: 23.0,
            non_offer_sale_seatprice: 20.0,
            non_offer_sale_surcharge: 3.0,
            number_available: 8,
            percentage_saving: 0,
            price_band_code: 'C/pool',
            price_band_desc: 'Band C',
            sale_combined: 23.0,
            sale_seatprice: 20.0,
            sale_surcharge: 3.0,
          },
        ],
        ticket_type_code: 'CIRCLE',
        ticket_type_desc: 'Upper circle',
      },
    ],
  },
  backend_is_broken: false,
  backend_is_down: false,
  backend_throttle_failed: false,
  contiguous_seat_selection_only: true,
  currency_code: 'gbp',
  currency_details: {
    gbp: {
      currency_code: 'gbp',
      currency_factor: 100,
      currency_number: 826,
      currency_places: 2,
      currency_post_symbol: '',
      currency_pre_symbol: '£',
    },
  },
  source_code: 'ext_test0',
  valid_quantities: [2, 3, 4, 5, 6, 7, 8],
};
